
- layout: left
  name: 네트워킹 & 보안
  description: |
    * VPN(IPsec, SSLVPN, Site-to-Site) 설계 및 배포
    * 방화벽 정책 설정 및 문제 해결
    * Routing, NAT, 보안그룹 운영

- layout: left
  name: 클라우드 플랫폼
  description: |
    * AWS VPC, CGW/VGW 구성
    * Azure Virtual Network 및 S2S VPN
    * GCP Cloud VPN 및 BGP 기반 라우팅

- layout: left
  name: 도구 & 자동화
  description: |
    * CLI 기반 VPN 구성 및 진단
    * Spirent TestCenter 성능 테스트 자동화

- layout: left
  name: 기타
  description: |
    * 리눅스 시스템 관리 (Ubuntu, CentOS)
    * Git 기반 설정 관리 및 문서화

- layout: left
  name: 백엔드
  description: |
    * Node.js(TypeScript)
    * PHP

- layout: left
  name: DevOps
  description: |
    * MySQL
    * EC2
