# Site
repository: https://github.com/jum94kr/jum94kr.github.io
# favicon: images/favicon.ico

# Personal info
name: HONG CHANG (TYLER) AN  
title: Network Engineer 
email: jum94kr@gmail.com
website: jum94kr.github.io
Phone: +82 10 5801 5164

# Social links
github_username:  jum94kr
linkedin_username: hongchangan

# About Section
# about_title: About Me
about_profile_image: images/myprofile.jpg
about_content: | # this will include new lines to allow paragraphs
 네트워크 엔지니어로서 지난 2년간 온프레미스와 클라우드 환경을 넘나들며 안정적인 VPN 인프라를 직접 설계하고 구축해왔습니다. 무엇이든 직접 손으로 해보며 배우는 걸 좋아하고, 복잡한 문제를 실용적으로 풀어내는 데에 자신이 있습니다. 지금도 현장에서 부딪히며 계속 배우고 성장 중입니다.

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience




  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
